from ao.players import players
from ao.model.entry import Entry
from . import draws

Nishioka = Entry(players.Nishioka, seed=31, draw=draws.MensSingles)
Khachanov = Entry(players.Khachanov, seed=18, draw=draws.MensSingles)
Hurkacz = Entry(players.Hurkacz, seed=10, draw=draws.MensSingles)
Korda = Entry(players.Korda, seed=29, draw=draws.MensSingles)
Tsitsipas = Entry(players.Tsitsipas, seed=3, draw=draws.MensSingles)
Sinner = Entry(players.Sinner, seed=15, draw=draws.MensSingles)
Lehecka = Entry(players.Lehecka, seed=None, draw=draws.MensSingles)
Auger_Aliassime = Entry(players.Auger_Aliassime, seed=6, draw=draws.MensSingles)
Rublev = Entry(players.Rublev, seed=5, draw=draws.MensSingles)
Rune = Entry(players.Rune, seed=9, draw=draws.MensSingles)
DeMinaur = Entry(players.DeMinaur, seed=22, draw=draws.MensSingles)
Djokovic = Entry(players.Djokovic, seed=4, draw=draws.MensSingles)
Shelton = Entry(players.Shelton, seed=None, draw=draws.MensSingles)
Wolf = Entry(players.Wolf, seed=None, draw=draws.MensSingles)
BautistaAgut = Entry(players.BautistaAgut, seed=24, draw=draws.MensSingles)
Paul = Entry(players.Paul, seed=None, draw=draws.MensSingles)

Swiatek = Entry(players.Swiatek, seed=1, draw=draws.WomensSingles)
Rybakina = Entry(players.Rybakina, seed=22, draw=draws.WomensSingles)
Ostapenko = Entry(players.Ostapenko, seed=17, draw=draws.WomensSingles)
Gauff = Entry(players.Gauff, seed=7, draw=draws.WomensSingles)
Pegula = Entry(players.Pegula, seed=3, draw=draws.WomensSingles)
Krejcikova = Entry(players.Krejcikova, seed=20, draw=draws.WomensSingles)
Azarenka = Entry(players.Azarenka, seed=24, draw=draws.WomensSingles)
Zhu = Entry(players.Zhu, seed=None, draw=draws.WomensSingles)
Pliskova = Entry(players.Pliskova, seed=30, draw=draws.WomensSingles)
Zhang = Entry(players.Zhang, seed=23, draw=draws.WomensSingles)
Linette = Entry(players.Linette, seed=None, draw=draws.WomensSingles)
Garcia = Entry(players.Garcia, seed=4, draw=draws.WomensSingles)
Sabalenka = Entry(players.Sabalenka, seed=5, draw=draws.WomensSingles)
Bencic = Entry(players.Bencic, seed=12, draw=draws.WomensSingles)
Vekic = Entry(players.Vekic, seed=None, draw=draws.WomensSingles)
Fruhvirtova = Entry(players.Fruhvirtova, seed=None, draw=draws.WomensSingles)
