from .match import Player

# Mens Singles Players

Nishioka = Player("Y. Nishioka", 31)
Khachanov = Player("K. Khachanov", 18)
Hurkacz = Player("H. Hurkacz", 10)
Korda = Player("S. Korda", 29)
Tsitsipas = Player("S. Tsitsipas", 3)
Sinner = Player("J. Sinner", 15)
Lehecka = Player("J. Lehecka", None)
Auger_Aliassime = Player("F. Auger-Aliassime", 6)
Rublev = Player("A. Rublev", 5)
Rune = Player("H. Rune", 9)
deMinaur = Player("A. de Minaur", 22)
Djokovic = Player("N. Djokovic", 4)
Shelton = Player("B. Shelton", None)
Wolf = Player("J. Wolf", None)
BautistaAgut = Player("R. Bautista Agut", 24)
Paul = Player("T. Paul", None)

# Womans Singles
Swiatek = Player("I. Swiatek", 1)
Rybakina = Player("E. Rybakina", 22)
Ostapenko = Player("J. Ostapenko", 17)
Gauff = Player("C. Gauff", 7)
Pegula = Player("J. Pegula", 3)
Krejcikova = Player("B. Krejcikova", 20)
Azarenka = Player("V. Azarenka", 24)
Zhu = Player("L. Zhu", None)
Pliskova = Player("K. Pliskova", 30)
Zhang = Player("S. Zhang", 23)
Linette = Player("M. Linette", None)
Garcia = Player("C. Garcia", 4)
Sabalenka = Player("A. Sabalenka", 5)
Bencic = Player("B. Bencic", 12)
Vekic = Player("D. Vekic", None)
Fruhvirtova = Player("L. Fruhvirtova", None)
